{{- if .Values.oodleConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: oodle-k8s-observability-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oodle-k8s-observability.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.oodleConfig.oodleApiKey | b64enc | quote }}
{{- end }}

